// Generated from Message.h

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;

namespace AllJoynDotNet
{
    [Flags]
    public enum MessageFlag : byte
    {
        /** No reply is expected */
        NoReplyExpected = 0x01,
        /** Auto start the service */
        AutoStart = 0x02,
        /** Allow messages from remote hosts (valid only in Hello message) */
        AllowRemoteMsg = 0x04,
        /** Sessionless message */
        Sessionless = 0x10,
        /** Global (bus-to-bus) broadcast */
        GlobalBroadcast = 0x20
    }
    public partial class Message 
    {
        public Message(BusAttachment bus) : base(alljoyn_message_create(bus.Handle))
        {
        }

        public MsgArg GetArgument(uint index)
        {
            return new MsgArg(alljoyn_message_getarg(Handle, (UIntPtr)index));
        }
        public string Signature
        {
            get
            {
                IntPtr sig = alljoyn_message_getsignature(Handle);
                return Marshal.PtrToStringAnsi(sig);
            }
        }
    }
}