// Generated from MsgArg.h

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;

namespace AllJoynDotNet
{
    public partial class MsgArg : AllJoynWrapper
    {
        public MsgArg() : base(alljoyn_msgarg_create())
        {

        }

        protected override void Dispose(bool disposing)
        {
            alljoyn_msgarg_destroy(Handle);
            base.Dispose(disposing);
        }

        public void Clear()
        {
            alljoyn_msgarg_clear(Handle);
        }
        public object Value
        {
            get
            {
                return TypeConversionHelpers.GetValueFromVariant(this, this.Signature);
            }
        }

        
        public string Signature
        {
            get
            {
                UIntPtr size = (UIntPtr)16;
                System.Text.StringBuilder sb = new System.Text.StringBuilder(256);
                var resultLength = (UInt64)alljoyn_msgarg_signature(Handle, sb, size + 1);
                return sb.ToString();
            }
        }
    }
}