// Generated from MsgArg.h

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.InteropServices;

namespace AllJoynDotNet
{
    public partial class MsgArg : AllJoynWrapper
    {
        protected override void Dispose(bool disposing)
        {
            alljoyn_msgarg_destroy(Handle);
            base.Dispose(disposing);
        }

        public void Clear()
        {
            alljoyn_msgarg_clear(Handle);
        }
    }
}